language: scala

scala:
    - 2.11.6

jdk:
    - oraclejdk8

script:
    - cd $TRAVIS_BUILD_DIR && ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test

after_success:
    - cd $TRAVIS_BUILD_DIR && ./sbt coveralls
