language: scala

scala:
    - 2.11.6

jdk:
    - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
    - sbt ++$TRAVIS_SCALA_VERSION clean sentinel/test sentinel/it:test
